### ISSUE TITLE
Incompatible with Microsoft Edge

### ISSUE THREAD

**Issue by Novantric** [SagaFreya/YouTubeDiscordRPC#4]
Runs perfectly, no issues or anything, but doesn't display in Discord.
Edge is my main and only browser right now, so this would be appreciated.
Thanks.

**Comment by seansev** [comment]
Well, I hate to be that guy, but my main recommendation is that you find a different browser. I have nothing against Edge but Microsoft made it very difficult to write programs for. I'd be willing to look into this if you really want, but I think it's unlikely that it's even possible with the system I used to detect tabs. Personally I'd recommend that you use either Firefox or a Chromium-based browser like Google Chrome or Opera, because those browsers support extensions and you could simply use [PreMiD](https://premid.app) instead of my crappy program. PreMiD is much more effective at detecting tabs and supports many different websites. Good luck with whatever you decide to do.
